### ISSUE TITLE
Transfer demo/bufferAll to mdn/dom-examples?

### ISSUE THREAD

**Issue by wbamberg** [nickdesaulniers/netfix#10]
Hi @nickdesaulniers !

Your example at https://github.com/nickdesaulniers/netfix/blob/gh-pages/demo/bufferAll.html is quoted on the MDN page at https://developer.mozilla.org/en-US/docs/Web/API/SourceBuffer#examples, which also links to this repo for the complete version. It's problematic for MDN maintainers for the example to live in a different repo, because we can't easily keep it in sync with the code in the page (and in fact they have already diverged quite a lot). See https://github.com/mdn/content/pull/30423 for some recent context.

Ideally we would transfer the example to the [mdn/dom-examples](https://github.com/mdn/dom-examples/) repo. Would you be OK with that? It means essentially putting this demo under a CC0 license, as that's what dom-examples uses.

Thank you!

**Comment by nickdesaulniers** [comment]
> Ideally we would transfer the example to the [mdn/dom-examples](https://github.com/mdn/dom-examples/) repo. Would you be OK with that?

Go for it!

**Comment by wbamberg** [comment]
Thank you! -> https://github.com/mdn/dom-examples/pull/239
